### PR TITLE
Port database.js to new DB structure

### PR DESCRIPTION
**Pull request by Digitalone1**
This is a first attempt to port `database.js` to new DB structure.

It seems we should implemented specific functions to create new package and return the new uuid.

@mauricioszabo take a look at it you too

### CODE REVIEW

**Review by confused-Techie — COMMENTED** [review]
This looks absolutely fantastic, thanks for your contributions!
Especially love the clever use of Ternary Operators to simplify the length check of a response, plus the use of the Nullish Coalescing Operator (which I've never seen before, and looks so helpful), and just now realizing about the SQL `IN` operation to collect all values within an array, which should be much more performant than the `for` loops I had implemented.

While I'd love to merge it, I want to get the changes to the Database done first, then go ahead and test this code before merging to main. But otherwise I see no faults, love it.

**Comment by Digitalone1** [comment]
- Please, could you explain what `getTotalPackageEstimate` is needed for? Count of all packages?
- We have a `getUserByName` function which returns a record looking by username. In order to work properly the username field must be unique even if it's not the primary key. The username could be modifiable, but still unique.  
- `verifyAuth` is getting the token from the database to verify the user, but for more safety it's better if we check also the username/uuid.
- Anyway I wonder if `verifyAuth` is really needed. If we previously pick the whole record looking by the username, can we just test against the `auth` field rather than calling another function and doing another query?   
- We have to remember that `downloads` and `stargazers_count` as **bigint** are returned as string for compatibility with `JSON.stringify` (se [here](https://github.com/porsager/postgres#numbers-bigint-numeric)), so if we have to handle them, we will have to convert to [Bigint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).  
- I wonder if `convertToUserFromDB` is really needed. Can't we just use the object and properties returned from the DB?

**Comment by confused-Techie** [comment]
@Digitalone1 these are all fantastic points
* `getTotalPackageEstimate` is used by `handlers/package_handler.js` to return the total amount of packages, to provide the `Link` Headers on some requests, so we will want to keep it, or a sufficient function around.
* As for `getUserByName` you are absolutely correct, and thats something that I didn't even consider. In that case, we should implement a constraint on the DB that all user names must be unique, and since at least for now, each username is based on the GitHub User name, GitHub is enforcing that for us, we will just have to check that it is during user creation, just in case.
* For `verifyAuth` I am still wondering if we should forgo the use of any tokens in the backend, and expect the user to provide to use a PAT token for the GitHub account, so that we don't have to manage these keys. But that does cause concern with breaking OAuth functionality so thats a hard one to say, would love to hear any ideas on it.
* As for if that is needed, the most common interaction for auth is just being passed the `auth` token, and finding the username via that field, since the username as far as I recall is never passed by a logged in user themselves, `getUserByName` is only used for `/api/users/:login/stars` which provides a username and expects their stars to be returned, in which case we never check the auth of the passed user, so we will still need `verifyAuth` in some form.
* As for `downloads` and `stargazers_count` you are absolutely correct, although I wonder if we ever actually interact with those values now that we can let the DB sort with them, do we need to? Since I'd think we are now just returning those values directly to the end user. But if we do deal with them, we may want to implement a helper function to convert to bigint.
* But lastly `convertToUserFromDB` is very pointless, before fully understanding the usage and returns from the DB, it was created, but now with a better understanding, knowing we can interact with these not as array objects, but standard objects in your implementation, we don't need to worry about that function. It was just made to avoid typing `command[0].username` like I had previously.

**Comment by Digitalone1** [comment]
> * `getTotalPackageEstimate` is used by `handlers/package_handler.js` to return the total amount of packages, to provide the `Link` Headers on some requests, so we will want to keep it, or a sufficient function around.

No problem, so the current query is enough for it.

> * As for `getUserByName` you are absolutely correct, and thats something that I didn't even consider. In that case, we should implement a constraint on the DB that all user names must be unique, and since at least for now, each username is based on the GitHub User name, GitHub is enforcing that for us, we will just have to check that it is during user creation, just in case.

Well, not only at user creation, but also when the user wants to change his/her name. Luckily the constrain will prevent to store the same name twice. Otherwise, we can still have multiple same usernames, but the search by name won't work properly.

> * As for if that is needed, the most common interaction for auth is just being passed the `auth` token, and finding the username via that field, since the username as far as I recall is never passed by a logged in user themselves, `getUserByName` is only used for `/api/users/:login/stars` which provides a username and expects their stars to be returned, in which case we never check the auth of the passed user, so we will still need `verifyAuth` in some form.

I suppose the token is unique, so I will restore the previous version without the name.

> * As for `downloads` and `stargazers_count` you are absolutely correct, although I wonder if we ever actually interact with those values now that we can let the DB sort with them, do we need to? Since I'd think we are now just returning those values directly to the end user. But if we do deal with them, we may want to implement a helper function to convert to bigint.

Maybe there's a way to update them directly inside the SQL query, so luckily we wouldn't handle them by JS. 

> * But lastly `convertToUserFromDB` is very pointless, before fully understanding the usage and returns from the DB, it was created, but now with a better understanding, knowing we can interact with these not as array objects, but standard objects in your implementation, we don't need to worry about that function. It was just made to avoid typing `command[0].username` like I had previously.

Okay, I will remove it.

**Comment by Digitalone1** [comment]
@confused-Techie updated with some fix needed for the database structure and added new remove package functions.

Tomorrow I will try to make the migration script.

I have a question anyway. What do we need `getPointerTable` for? Is it really necessary?

**Review by confused-Techie — APPROVED** [review]
This looks fantastic!

Great commit, especially appreciate the documentation links for some lesser known code features being used. Otherwise this all looks rad. And I'm tempted to merge to main so I can begin utilizing these features in other locations in the meantime to help us get going and we then test once the database is migrated. 

Otherwise to answer your question about `getPointerTable` the idea there is to allow us to use the custom search features on the package names. Meaning we could collect an array of all package names via the table, run our search against each item and then we have a custom ranking of the packages, which we then in some way translate to returning the packages in that order. It may need some refinement but thats the basic idea

But if theres a better or especially simpler way you can think to implement this I'm not attached to that idea of functionality. Would just hate to lose the custom search engine thats been implemented. But if we do use this and testing shows the performance is terrible we could switch over to the native search of Postgresql

**Comment by Digitalone1** [comment]
> Otherwise to answer your question about `getPointerTable` the idea there is to allow us to use the custom search features on the package names. Meaning we could collect an array of all package names via the table, run our search against each item and then we have a custom ranking of the packages, which we then in some way translate to returning the packages in that order. It may need some refinement but thats the basic idea
> 
> But if theres a better or especially simpler way you can think to implement this I'm not attached to that idea of functionality. Would just hate to lose the custom search engine thats been implemented. But if we do use this and testing shows the performance is terrible we could switch over to the native search of Postgresql

I don't remember at the moment, but which is this custom search engine?

**Comment by confused-Techie** [comment]
Merging this PR, and opening an issue to continue discussion about the search features.

**Pull request merged**
