### PR TITLE
Adhere to JS standard

### PR DESCRIPTION
**Pull request by Digitalone1**
Related to #32 

Some errors may show up, but most of the work is done. Fortunately with regex and Atom search and replace the work has been easier, but it took quite an hour anyway.

I left functions like `GETPackages`/`POSTPackages` as is because I don't know how to change them. `gETPackages`?

### CODE REVIEW

**Comment by autumnblazey** [comment]
`getPackages` and `postPackages`? I think this is generally how people do it

**Comment by confused-Techie** [comment]
This is a fantastic commit. Really a huge amount of work so thank you. But @autumnblazey is correct on how we will want to change the naming to `getPackages` and additionally will want to get things like `POFPrune` to probably `prunePOF` since `POF` or `POS` are acronyms. 

Otherwise absolutely fantastic work!
But don't worry about errors, some actions are already failing, since its mid-migration to the DB. Thanks a ton

**Comment by Digitalone1** [comment]
> `getPackages` and `postPackages`? I think this is generally how others do it

Sure, but we loose the emphasis on the http method.

**Comment by autumnblazey** [comment]
i suppose so, unfortunately >~<

**Pull request merged**
