### PR TITLE
Test contribution

### PR DESCRIPTION
**Pull request by Digitalone1**
@confused-Techie let me know if this is acceptable.

If the argument can also be a number for some of the methods, some rework is needed.

If it's okay for you, I'd like to convert `"undefined"` to `undefined` where it's convenient. 

Edit: And also make some local var as `let`.

### CODE REVIEW

**Comment by confused-Techie** [comment]
This looks good, one thing that was unclear in its current state is that the engine should return its value, rather than just true or false, it just has no default, so it returns false if non-existent, but otherwise this looks great, and I'll make that simple change then merge. Thanks so much for your contribution!

**Comment by Digitalone1** [comment]
Okay, feel free to change the let to var if this is your habit.

For `undefined`, I think it's better without the double quotes. Will make a change to all of them.

**Comment by Digitalone1** [comment]
I gave another look, you forgot to add the period to the regex for `repo()`.

**Comment by confused-Techie** [comment]
@Digitalone1 thanks for reminding me, I'll put this on my todo tomorrow. But the undefined is a bit easier to read in an editor without the quotes and makes no real difference. But I'm reading more about the usage of 'let', and realistically I'll leave those changes in since there's no huge difference, just may put 'var' in myself at times. But thanks for calling my attention to it.

**Pull request merged**
